export const TILE_SIZE = 64;

export const ASSETS = {
  BUTTON_PRESSED: 11,
  BUTTON_RELEASED: 12,
  BUTTON_BASE: 13,
  DOOR_OPEN: 14,
  CRATE: 16,
  POINT_BUTTON: 18,
  DOOR_CLOSED: 19,
};

const ASSETS_TILE_SIZE = 24;
export const SCALE_FACTOR = TILE_SIZE / ASSETS_TILE_SIZE;
